'poor mans's DB lock: lock the right DB
See #252 where the following error was triggered:

> django.db.transaction.TransactionManagementError: select_for_update cannot be
> used outside of a transaction.

I believe that this is caused by using a non-sqlite database for the snappea DB.
"You probably shouldn't" but at least our own behavior should be consistent.

I haven't been able to reproduce this particular error BTW, but at least I've
reproduced _some_ error conditions that this commit fixes.