Wrap one more BASE_URL usages with str()
In 59372aba3381 a lazily evaluated BASE_URL tool was introduced.
I found 1 more case in which BASE_URL was not "collapsed into a
string" magically by `__add__`, causing an
`AttributeError: 'TenantBaseURL' object has no attribute 'decode'`